use_frameworks!
platform :ios, '10.0'

target 'ShadowRadar_Example' do
    pod 'SnapKit'
    pod 'ShadowRadar/Title', :path => '../'

    target 'ShadowRadar_Tests' do
        inherit! :search_paths
    end
end
